nnom-models: Try to get MobileNet working
Currently fails to generate a model

    File "../nnom-models/auto_test/venv/lib/python3.11/site-packages/nnom/nnom.py", line 731, in quantize_weights
      f.write('#define ' + layer.name.upper() + '_BIAS_LSHIFT '+to_cstyle(bias_shift) +'\n\n')
                                                                        ^^^^^^^^^^
   UnboundLocalError: cannot access local variable 'bias_shift' where it is not associated with a value

MobileNet does not use bias for Conv layers. Currently that is not supported in NNoM,
and might be the reason of this error.

Ref https://github.com/majianjia/nnom/issues/80